minor changes

diff --git a/.github/workflows/deploy-parameter-store.yaml b/.github/workflows/deploy-parameter-store.yaml
--- a/.github/workflows/deploy-parameter-store.yaml
+++ b/.github/workflows/deploy-parameter-store.yaml
@@ -26,7 +26,7 @@ env:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-    environment: ${{ github.event.inputs.environment }}
+    environment: ${{ github.event.inputs.environment || 'qa' }}
 
     permissions:
       id-token: write
@@ -52,6 +52,11 @@ jobs:
         run: |
           SCOPE="${{ github.event.inputs.scope }}"
           DEPLOY_ENV="${{ github.event.inputs.environment }}"
+
+          if [ "$SCOPE" == "env" ] && [ -z "$DEPLOY_ENV" ]; then
+            echo "ERROR: environment must be selected when scope=env"
+            exit 1
+          fi
 
           if [ "$SCOPE" == "common" ]; then
             STACK_NAME="parameter-store-common"
